{"name": "test_create_user_with_valid_values", "status": "failed", "statusDetails": {"message": "AssertionError: User already exist\nassert 422 == 201", "trace": "set_environment_variable = 'stag'\n\n    @allure.severity(severity_level=\"Critical\")\n    def test_create_user_with_valid_values(set_environment_variable):\n        endpoint = TestData().get_endpoint_env(\"stag\", 'create_user')\n        payload = TestData().payload_method()\n        header = TestData().header_method()\n    \n        payload['id'] = '5818268'\n        payload['name'] = 'ra__erma'\n        payload['email'] = 'ddrrtyrdd@gmail.com'\n        payload['gender'] = 'male'\n        payload['status'] = 'active'\n        payload_json = json.dumps(payload)\n        response = requests.request(\"POST\", endpoint, headers=header, data=payload_json)\n        res_dict = response.json()\n        response_code = response.status_code\n>       assert response_code == 201, \"User already exist\"\nE       AssertionError: User already exist\nE       assert 422 == 201\n\nTest_case\\test_create_user.py:36: AssertionError"}, "start": 1703345474516, "stop": 1703345475155, "uuid": "38843c5b-914e-412b-ae89-e2d7ce25e867", "historyId": "c4528f1fcc5809fc1e39d09a583baa8d", "testCaseId": "c4528f1fcc5809fc1e39d09a583baa8d", "fullName": "Test_case.test_create_user#test_create_user_with_valid_values", "labels": [{"name": "severity", "value": "Critical"}, {"name": "parentSuite", "value": "Test_case"}, {"name": "suite", "value": "test_create_user"}, {"name": "host", "value": "devshakya"}, {"name": "thread", "value": "2660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_case.test_create_user"}]}